#!/bin/sh
echo 1 > /proc/sys/net/ipv4/ip_forward

#Allow incoming connnections on LAN
iptables -A INPUT -i eth0 -j ACCEPT
iptables -A OUTPUT -o eth0 -j ACCEPT
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

# Allow established sessions to receive traffic
iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

#NAT
iptables -t nat -A POSTROUTING -o usbnet0 -j MASQUERADE

#default policy drop
iptables -P INUPT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT ACCEPT

#IPV6

# Allow established connections
ip6tables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
ip6tables -A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT

# Allow ICMPv6 traffic (required for IPv6) This could be tightened up but it must
# be done very carefully unless you know what you're doing. It could block all
# routing
ip6tables -A INPUT -p ipv6-icmp -j ACCEPT
ip6tables -A FORWARD -p ipv6-icmp -j ACCEPT

#default policy drop
ip6tables -P INUPT DROP
ip6tables -P FORWARD DROP
ip6tables -P OUTPUT ACCEPT